### PR TITLE
Fix gnome-shell's breaking change

### PR DESCRIPTION
**Pull request by soraxas**
This PR updates code base to fix the gnome-shell's breaking changes to the class structure, which causes the latest gnome-shell not working (#66).

Fixes are made based on suggestion on [this](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/551#issuecomment-558302621).

### CODE REVIEW

**Comment by LaurentOngaro** [comment]
Hi,

@soraxas Thanks for your work for making it compatible with last gnome shell version !

Using your code, the display is fixed and runs well, but on my PC, editing or adding tasks crashes gnome shell with no message.
I'm using Arch Linux and Gnome, both are up to date.

**Comment by soraxas** [comment]
I am using Arch as well. Do you have any logs for it? You can use journalctl to view gnome shell's log

**Comment by LaurentOngaro** [comment]
I've just checked the journal just after a crash and I see no error , just some warnings

here the result of : `journalctl -rx -g taskwhisperer`. 
If you know a better to way to have more logs, just tell me
`-- Logs begin at Thu 2020-01-30 09:20:14 CET, end at Thu 2020-01-30 13:48:12 CET. --
janv. 30 13:42:36 NomaTicArco gnome-shell[22812]: JS WARNING: [/home/focus/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/spawnReader.js 10]: assignment to undeclared variable res
janv. 30 13:42:36 NomaTicArco gnome-shell[22812]: JS WARNING: [/home/focus/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js 104]: Too many arguments to method Clutter.Container.add_actor>
janv. 30 13:42:36 NomaTicArco gnome-shell[22812]: Usage of object.actor is deprecated for TaskWhispererMenuButton
                                                  get@resource:///org/gnome/shell/ui/environment.js:249:29
                                                  _init@/home/focus/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:761:17
                                                  enable@/home/focus/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:1043:25
                                                  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:280:21
                                                  _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:490:13
                                                  collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                                  _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:469:9
                                                  _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:499:13
                                                  _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:530:13
                                                  init@resource:///org/gnome/shell/ui/extensionSystem.js:48:9
                                                  _initializeUI@resource:///org/gnome/shell/ui/main.js:242:5
                                                  start@resource:///org/gnome/shell/ui/main.js:138:5
                                                  @<main>:1:31
janv. 30 13:42:36 NomaTicArco gnome-shell[22812]: Usage of object.actor is deprecated for TaskWhispererMenuButton
                                                  get@resource:///org/gnome/shell/ui/environment.js:249:29
                                                  _init@/home/focus/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:746:9
                                                  enable@/home/focus/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:1043:25
                                                  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:280:21
                                                  _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:490:13
`

**Comment by LaurentOngaro** [comment]
FYI, 

I've used a git clone to get the source code and copied it to `~/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de`

I can edit or add tasks using shell commands without issue
Creating tasks using the "task warrior integration" gnome shell extension runs well
I use a custom location for the tasks folder (so not the `~ /.task` folder)

**Comment by soraxas** [comment]
Hey @LaurentOngaro try to use the latest commit version. 

It should now fix the issues with those functions (it was because the dialogs for *creating* and *modifing* task were still using the old deprecated class style)

**Comment by LaurentOngaro** [comment]
I've made a quick test and all seems to work fine. 
Thank for your work on a so useful extension

**Comment by ghost** [comment]
good work, thanks @soraxas

**Comment by LaurentOngaro** [comment]
It seems that issue is still present in `cinatic:master`
SEE https://github.com/cinatic/taskwhisperer/issues/66#issuecomment-581850567

**Pull request merged**
